### ISSUE TITLE
Add MaskAnyoneUI Pose Estimator

### ISSUE THREAD

**Issue by TimRiedel** [maskbench/maskbench#49]
### Description
According to the MaskBench pipeline, the user has to "manually" annotate a dataset, store it manually, but then be able to "upload" this dataset to maskbench to be included in the evaluation.

### Acceptance Criteria
- [x] Create a `MaskAnyoneUIPoseEstimator`, which has as config the path to the human-annotated dataset. Like so:
```
  - name: MaskAnyoneUI
    enabled: true
    module: models.mask_anyone_ui_pose_estimator
    class: MaskAnyoneUIPoseEstimator
    config:
      dataset_path: # user configurable
```
- [x] The dataset likely contains multiple videos. It might also be that it contains multiple chunks per videos aka multiple pose files. Loading this human-annotated dataset involves re-assembling the pose files into one file we can use for evaluation. Dependency: #28
